service: io-klerch-alexa-once

provider:
  name: aws
  stage: prod
  runtime: nodejs6.10
  region: eu-west-1
  memorySize: 1536 
  timeout: 20 
  versionFunctions: false 
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - s3:GetObject
      Resource: "arn:aws:s3:::io.klerch.alexa.once/*"

functions:
  history:
    name: ${self:service}-prod-feed
    handler: handler.feed
    events:
      - http:
          path: history
          method: get
      - http:
          path: sports
          method: get
      - http:
          path: birthdays
          method: get
      - http:
          path: culture
          method: get
      - http:
          path: science
          method: get
      - http:
          path: economics
          method: get